# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '_checkbox.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(528, 437)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btnKaydet = QtWidgets.QPushButton(self.centralwidget)
        self.btnKaydet.setGeometry(QtCore.QRect(90, 220, 56, 17))
        self.btnKaydet.setObjectName("btnKaydet")
        self.lblresult = QtWidgets.QLabel(self.centralwidget)
        self.lblresult.setGeometry(QtCore.QRect(180, 260, 161, 111))
        self.lblresult.setObjectName("lblresult")
        self.hobiler = QtWidgets.QGroupBox(self.centralwidget)
        self.hobiler.setGeometry(QtCore.QRect(10, 30, 241, 171))
        self.hobiler.setObjectName("hobiler")
        self.widget = QtWidgets.QWidget(self.hobiler)
        self.widget.setGeometry(QtCore.QRect(20, 20, 191, 131))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.cbSinema = QtWidgets.QCheckBox(self.widget)
        self.cbSinema.setObjectName("cbSinema")
        self.verticalLayout.addWidget(self.cbSinema)
        self.cbKitap = QtWidgets.QCheckBox(self.widget)
        self.cbKitap.setObjectName("cbKitap")
        self.verticalLayout.addWidget(self.cbKitap)
        self.cbSpor = QtWidgets.QCheckBox(self.widget)
        self.cbSpor.setObjectName("cbSpor")
        self.verticalLayout.addWidget(self.cbSpor)
        self.dersler = QtWidgets.QGroupBox(self.centralwidget)
        self.dersler.setGeometry(QtCore.QRect(250, 40, 241, 161))
        self.dersler.setObjectName("dersler")
        self.layoutWidget = QtWidgets.QWidget(self.dersler)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 20, 191, 131))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.cbWeb = QtWidgets.QCheckBox(self.layoutWidget)
        self.cbWeb.setObjectName("cbWeb")
        self.verticalLayout_2.addWidget(self.cbWeb)
        self.cbProgramlama = QtWidgets.QCheckBox(self.layoutWidget)
        self.cbProgramlama.setObjectName("cbProgramlama")
        self.verticalLayout_2.addWidget(self.cbProgramlama)
        self.cbMatematik = QtWidgets.QCheckBox(self.layoutWidget)
        self.cbMatematik.setObjectName("cbMatematik")
        self.verticalLayout_2.addWidget(self.cbMatematik)
        self.btnKaydet_2 = QtWidgets.QPushButton(self.centralwidget)
        self.btnKaydet_2.setGeometry(QtCore.QRect(320, 220, 56, 17))
        self.btnKaydet_2.setObjectName("btnKaydet_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 528, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btnKaydet.setText(_translate("MainWindow", "Kaydet"))
        self.lblresult.setText(_translate("MainWindow", "Seçilenler: "))
        self.hobiler.setTitle(_translate("MainWindow", "GroupBox"))
        self.cbSinema.setText(_translate("MainWindow", "Sinema"))
        self.cbKitap.setText(_translate("MainWindow", "Kitap,"))
        self.cbSpor.setText(_translate("MainWindow", "Spor"))
        self.dersler.setTitle(_translate("MainWindow", "GroupBox"))
        self.cbWeb.setText(_translate("MainWindow", "Web Tasarım"))
        self.cbProgramlama.setText(_translate("MainWindow", "Programlama"))
        self.cbMatematik.setText(_translate("MainWindow", "Matematik"))
        self.btnKaydet_2.setText(_translate("MainWindow", "Kaydet"))
