# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

# pyuic5 dosya_adı.ui -o dosya_adı.py --> ui dosyasından py dosyası oluşturma

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(449, 312)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.txt_num1 = QtWidgets.QLabel(self.centralwidget)
        self.txt_num1.setGeometry(QtCore.QRect(50, 40, 80, 40))
        self.txt_num1.setObjectName("txt_num1")
        self.txt_num2 = QtWidgets.QLabel(self.centralwidget)
        self.txt_num2.setGeometry(QtCore.QRect(50, 90, 80, 40))
        self.txt_num2.setObjectName("txt_num2")
        self.lbl_num1 = QtWidgets.QLineEdit(self.centralwidget)
        self.lbl_num1.setGeometry(QtCore.QRect(100, 50, 120, 20))
        self.lbl_num1.setObjectName("lbl_num1")
        self.lbl_num2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lbl_num2.setGeometry(QtCore.QRect(100, 90, 120, 20))
        self.lbl_num2.setObjectName("lbl_num2")
        self.btn_add = QtWidgets.QPushButton(self.centralwidget)
        self.btn_add.setGeometry(QtCore.QRect(70, 140, 56, 17))
        self.btn_add.setObjectName("btn_add")
        self.btn_sub = QtWidgets.QPushButton(self.centralwidget)
        self.btn_sub.setGeometry(QtCore.QRect(140, 140, 56, 17))
        self.btn_sub.setObjectName("btn_sub")
        self.btn_mul = QtWidgets.QPushButton(self.centralwidget)
        self.btn_mul.setGeometry(QtCore.QRect(210, 140, 56, 17))
        self.btn_mul.setObjectName("btn_mul")
        self.btn_div = QtWidgets.QPushButton(self.centralwidget)
        self.btn_div.setGeometry(QtCore.QRect(280, 140, 56, 17))
        self.btn_div.setObjectName("btn_div")
        self.lbl_result = QtWidgets.QLabel(self.centralwidget)
        self.lbl_result.setGeometry(QtCore.QRect(150, 190, 91, 51))
        self.lbl_result.setObjectName("lbl_result")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 449, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.txt_num1.setText(_translate("MainWindow", "Sayı 1:"))
        self.txt_num2.setText(_translate("MainWindow", "Sayı 2:"))
        self.btn_add.setText(_translate("MainWindow", "+"))
        self.btn_sub.setText(_translate("MainWindow", "-"))
        self.btn_mul.setText(_translate("MainWindow", "x"))
        self.btn_div.setText(_translate("MainWindow", "/"))
        self.lbl_result.setText(_translate("MainWindow", "Sonuç: "))
